version: '3'
services:
  web:
    image: php:8.3-apache
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - URL=${URL}
    command: sh -c "chmod -R 777 /var/www/html && apache2-foreground"
